//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=46fc1a90-01b6-48fa-bcf4-a637014000a3.sqlserver.sequelizer.com;Initial" +
            " Catalog=db46fc1a9001b648fabcf4a637014000a3;User ID=gsoubteozzmmmsic;Password=Ux" +
            "FfFFDRUBibwuoaBLfJNjHgCASxZCTsUfWwrueRoYdJKimKPBb2LSyKXzJeVfZr;MultipleActiveRes" +
            "ultSets=True")]
        public string connString {
            get {
                return ((string)(this["connString"]));
            }
        }
    }
}
